services:
  femto_bolt_orbbec_camera:
    build: .
    container_name: femto_bolt_orbbec_camera
    runtime: nvidia
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: >
      ros2 launch orbbec_camera femto_bolt.launch.py
      depth_registration:=true
      enable_point_cloud:=true
      enable_colored_point_cloud:=true
      ordered_pc:=false
      depth_registration:=true
      enable_noise_removal_filter:=true
      enable_decimation_filter:=false
      decimation_filter_scale:=4
  femto_bolt_rviz:
    image: osrf/ros:humble-desktop
    container_name: femto_bolt_rviz
    network_mode: host
    ipc: host
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rviz2
